CREATE TABLE CATEGORY
(
	IDCATEGORY INT NOT NULL IDENTITY,
	CATEGORYNAME NVARCHAR(100)

	CONSTRAINT PK_CATEGORY
	PRIMARY KEY (IDCATEGORY)
)

CREATE TABLE PRODUCT
(
	IDPRODUCT INT NOT NULL IDENTITY,
	IDCATEGORY INT,
	PRODUCTNAME NVARCHAR(MAX),
	PRICE INT,
	DESCRIPTION NVARCHAR(MAX),
	IMAGE VARCHAR(MAX),

	 CONSTRAINT PK_PRODUCT
	PRIMARY KEY (IDPRODUCT)
)



CREATE TABLE SIZEPRODUCT
(
	IDPRODUCT INT,
	SIZE VARCHAR(10),
	QUANTITY INT,

	CONSTRAINT PK_SIZEPRODUCT
	PRIMARY KEY (IDPRODUCT,SIZE)

)

CREATE TABLE ORDERS
(
	IDORDER INT NOT NULL IDENTITY,
	CUSTOMERNAME NVARCHAR(100),
	ADDRESS NVARCHAR(MAX),
	EMAIL VARCHAR(100),
	NOTE NVARCHAR(MAX),
	TOTAL INT,
	STATUS INT,
	DATE VARCHAR(10)

	CONSTRAINT PK_ORDER
	PRIMARY KEY (IDORDER)
)

CREATE TABLE DETAILORDER
(
	IDORDER INT,
	IDPRODUCT INT,
	QUATITY INT,
	TOTALPRICE INT
	
	CONSTRAINT PK_DETAILORDER
	PRIMARY KEY (IDORDER,IDPRODUCT)
)

CREATE TABLE IMAGES
(
	IDPRODUCT INT,
	IMAGE VARCHAR(MAX)
)

ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY(IDCATEGORY) REFERENCES CATEGORY(IDCATEGORY)

ALTER TABLE SIZEPRODUCT ADD CONSTRAINT FK_SIZEPRODUCT_PRODUCT FOREIGN KEY(IDPRODUCT) REFERENCES PRODUCT(IDPRODUCT)

ALTER TABLE DETAILORDER ADD CONSTRAINT FK_DETAILPRODUCT_ORDERS FOREIGN KEY(IDORDER) REFERENCES ORDERS(IDORDER)

ALTER TABLE DETAILORDER ADD CONSTRAINT FK_DETAILPRODUCT_PRODUCT FOREIGN KEY(IDPRODUCT) REFERENCES PRODUCT(IDPRODUCT)

ALTER TABLE IMAGES ADD CONSTRAINT FK_IMAGES_PRODUCT FOREIGN KEY (IDPRODUCT) REFERENCES  PRODUCT(IDPRODUCT)

alter table DETAILORDER drop constraint FK_DETAILPRODUCT_PRODUCT

drop table DETAILORDER